[package]
name = "rustygb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib/lib.rs"

[dependencies]
hashbrown = "0.14"

[dev-dependencies]
minifb = "0.25"
